# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 10:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('company_name', models.CharField(max_length=255, unique=True, verbose_name='Company Name')),
                ('addr_street', models.CharField(max_length=255, verbose_name='Street')),
                ('addr_zip_code', models.PositiveIntegerField(verbose_name='ZIP Code')),
                ('addr_city', models.CharField(max_length=255, verbose_name='City')),
                ('addr_country', models.CharField(max_length=30, verbose_name='Country')),
                ('vat_no', models.CharField(max_length=15, verbose_name='VAT No.')),
                ('website', models.URLField(max_length=255, verbose_name='Website')),
                ('invoice_mail', models.EmailField(max_length=255, verbose_name='Invoice E-mail')),
                ('invoice_conctact_name', models.CharField(max_length=255, verbose_name='Invoice Contact Name')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='CompanySizeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('size_from', models.PositiveIntegerField()),
                ('size_to', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanySystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('system_name', models.CharField(max_length=255, verbose_name='Name')),
                ('reception', models.BooleanField(verbose_name='Reception')),
                ('registration', models.BooleanField(verbose_name='Registration')),
                ('storage', models.BooleanField(verbose_name='Storage')),
                ('deletion', models.BooleanField(verbose_name='Deletion')),
                ('passing', models.BooleanField(verbose_name='Passing')),
                ('system_location', models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], max_length=20, verbose_name='System Location')),
                ('active', models.BooleanField(verbose_name='Active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkivo_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkivo_app.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='company_size_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkivo_app.CompanySizeRange', verbose_name='Company Size'),
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together=set([('user', 'company')]),
        ),
        migrations.AlterUniqueTogether(
            name='companysystem',
            unique_together=set([('company', 'system_name')]),
        ),
    ]
