# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkivo_app', '0002_auto_20170917_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
