# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arkivo_app', '0005_project_survey_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='companysystem',
            old_name='system_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='companysystem',
            unique_together=set([('company', 'name')]),
        ),
    ]
