# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arkivo_app', '0006_auto_20170919_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkivo_app.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='company',
            new_name='active_company',
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkivo_app.UserProfile'),
        ),
    ]
