# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkivo_app', '0007_auto_20170920_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='view_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
