# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arkivo_app', '0013_auto_20170921_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arkivo_app.SurveySection'),
            preserve_default=False,
        ),
    ]
