# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkivo_app', '0016_auto_20170921_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncategory',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
