# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkivo_app', '0017_auto_20170921_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='surveysection',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
